/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jitbuilder_release_java_include_MethodHandler */

#ifndef _Included_jitbuilder_release_java_include_MethodHandler
#define _Included_jitbuilder_release_java_include_MethodHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jitbuilder_release_java_include_MethodHandler
 * Method:    invoke
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jitbuilder_release_java_include_MethodHandler_invoke
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
