/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jitbuilder_release_java_include_IlType */

#ifndef _Included_jitbuilder_release_java_include_IlType
#define _Included_jitbuilder_release_java_include_IlType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jitbuilder_release_java_include_IlType
 * Method:    setClientObj
 * Signature: (Ljitbuilder/release/java/include/IlType;J)V
 */
JNIEXPORT void JNICALL Java_jitbuilder_release_java_include_IlType_setClientObj
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     jitbuilder_release_java_include_IlType
 * Method:    impl_initializeFromImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jitbuilder_release_java_include_IlType_impl_1initializeFromImpl
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
