/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jitbuilder_release_java_include_VirtualMachineOperandStack */

#ifndef _Included_jitbuilder_release_java_include_VirtualMachineOperandStack
#define _Included_jitbuilder_release_java_include_VirtualMachineOperandStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jitbuilder_release_java_include_VirtualMachineOperandStack
 * Method:    impl_initializeFromImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jitbuilder_release_java_include_VirtualMachineOperandStack_impl_1initializeFromImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jitbuilder_release_java_include_VirtualMachineOperandStack
 * Method:    getClientObj
 * Signature: (J)Ljitbuilder/release/java/include/IlValue;
 */
JNIEXPORT jobject JNICALL Java_jitbuilder_release_java_include_VirtualMachineOperandStack_getClientObj
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jitbuilder_release_java_include_VirtualMachineOperandStack
 * Method:    setClientObj
 * Signature: (Ljitbuilder/release/java/include/VirtualMachineOperandStack;J)V
 */
JNIEXPORT void JNICALL Java_jitbuilder_release_java_include_VirtualMachineOperandStack_setClientObj
  (JNIEnv *, jclass, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
