/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IlBuilder_JBCondition */

#ifndef _Included_IlBuilder_JBCondition
#define _Included_IlBuilder_JBCondition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IlBuilder_JBCondition
 * Method:    impl_initializeFromImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_IlBuilder_00024JBCondition_impl_1initializeFromImpl
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
