/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IlBuilder_JBCase */

#ifndef _Included_IlBuilder_JBCase
#define _Included_IlBuilder_JBCase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IlBuilder_JBCase
 * Method:    impl_initializeFromImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_IlBuilder_00024JBCase_impl_1initializeFromImpl
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
