/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jitbuilder_release_java_samples_Simple */

#ifndef _Included_jitbuilder_release_java_samples_Simple
#define _Included_jitbuilder_release_java_samples_Simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jitbuilder_release_java_samples_Simple
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jitbuilder_release_java_samples_Simple_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
