/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JitBuilder */

#ifndef _Included_JitBuilder
#define _Included_JitBuilder
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     JitBuilder
 * Method:    initializeJit
 * Signature: ()Z
 */
  JNIEXPORT jboolean JNICALL Java_JitBuilder_initializeJit(JNIEnv *, jclass);

  /*
 * Class:     JitBuilder
 * Method:    shutdownJit
 * Signature: ()Z
 */
  JNIEXPORT jboolean JNICALL Java_JitBuilder_shutdownJit(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
