/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MethodHandler */

#ifndef _Included_MethodHandler
#define _Included_MethodHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MethodHandler
 * Method:    invoke
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MethodHandler_invoke
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
